version: '3.9'

services:
  postgres:
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=currency_api'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres